[build]
  base = "admin_dashboard"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
